# Scikit_Learn 맛보기
## Iris 분류 - 결정트리, 서포트벡터머신(SWM), 로지스틱 회귀

### 1. 데이터 전처리

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
# 사이킷에서는 seaborn 말고 이렇게 데려옴

In [2]:
type(iris)

sklearn.utils.Bunch

In [20]:
dict.keys(iris)     # inside iris 

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# Feature data - X 값 
iris.data.shape         # X값은 iris.data, shape은 size 알기위해서 4개

(150, 4)

In [5]:
# Feature name
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
# target data - y 값 (세토사, 버지칼라, 버지니카...)
iris.target.shape
# 150개 라는 뜻 

(150,)

In [10]:
import pandas as pd 
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target                              # df[''] : df에 열추가
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
# Target name 
iris.target_names
# 인덱스 0 : 세토사, 1 : 버지니카 ... 이런 식 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
# 설명 
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### 2. 학습용 데이터와 테스트용 데이터 분리

In [35]:
from sklearn.model_selection import train_test_split    # 절대 이걸 입력하지X
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, random_state=2021
)

# 어떤 모듈이 어떤 툴에 있는지 외으고 익숙해기(94p)
# 이건 좀 외우래 


In [22]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape
# X = 2차원, Y = 1차원 

((112, 4), (38, 4), (112,), (38,))

In [24]:
y_test

# 품종별 인덱스가 마구 섞여서 나온다는 점

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       2, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0])

In [27]:
# (y_train) array 속 0 갯수 구하기 
# 넘파이 array
import numpy as np
np.unique(y_train)

array([0, 1, 2])

In [28]:
np.unique(y_train, return_counts=True)

# 뽑아낸 숫자를 보니 랜덤하게 뽑아냈음을 알 수 있음 

(array([0, 1, 2]), array([34, 36, 42], dtype=int64))

In [29]:
# 옵션주기 
X_train, X_test, y_train, y_test = train_test_split(
        iris.data, iris.target, random_state= 2021,
        test_size=0.2, stratify=iris.target
)

# test_size = 0.2 : 전체 데이터 셋의 20%를 test로 주겠다 
# stratify = iris.target : (target값을 균일하게 나눠주기)데이터를 분포를 동일하게 해주는 stratify


In [30]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

### 3. 학습 

- Decision Tree 

In [32]:
from sklearn.tree import DecisionTreeClassifier

#사이킷런의 트리모듈 속 Decision~fier (대문자:class)
#'디시전으로 학습을 시키겠다'

In [33]:
# 모델 생성 = 객체를 만드는 작업 
dtc = DecisionTreeClassifier(random_state=2021)     # 괄호 안은 하이퍼 파라메터 (옵션임)


In [34]:
# 학습 
dtc.fit(X_train, y_train)
# X,y순으로 들어감을 fit 학습 메소드 타자치면 설명으로 뜸

DecisionTreeClassifier(random_state=2021)

### 4. 예측 

- 예측은 테스트 데이터로 합니다. 

In [43]:
pred_dt = dtc.predict(X_test)
# 어떤 test를 넣는게 합리적인가... X! 

In [45]:
df = pd.DataFrame({'y': y_test, 'DT': pred_dt})
df.head()

y  DT
0  0   0
1  1   1
2  1   2
3  2   2
4  0   0

### 5. 평가 - 예측값과 실제값을 비교해서 모델 성능 평가 

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_dt)

# 90% 동일함 

0.9

In [50]:
# 4,5를 한꺼번에 수행
dtc.score(X_test, y_test)

0.9

### SVM(Support Vector Machine)으로 3,4,5 과정을 수행

In [51]:
from sklearn.svm import SVC
svc = SVC(random_state=2021) # 모델 만들기(랜덤) 
svc.fit(X_train, y_train) # 학습 


SVC()

In [52]:
pred_sv = svc.predict(X_test)
accuracy_score(y_test, pred_sv)

0.9

### Logistic Regression 으로 3,4,5 과정을 수행

In [53]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=2021)    # 모델 만들어주기(랜덤) 
lrc.fit(X_train, y_train)                       # 학습


C:\Users\ICT01_11\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=2021)

In [54]:
# 에러가 납니다. 
# max_iter (리미트가 한 300 정도라고 함 )

In [55]:
# 해결책1 - max_iter 하이퍼 파라메터 값 조정(=1000)
lrc2 = LogisticRegression(random_state=2021, max_iter=1000)     # 에러코드 읽어보면 max_iter 리미트에 닿았다고 함.
lrc2.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=2021)

In [75]:
# 해결책 2로 예측하기(해결책 2 다시해주는 과정 하고 다시 올라옴)
pred_lr2 = lrc2.predict(X_test)
accuracy_score(y_test, pred_lr2)

0.9333333333333333

In [58]:
# 해결책2 - 데이터 전처리를 해줄 것 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
iris_std = scaler.fit_transform(iris.data)

# 스탠다드 스케일러/ 분포(스케일)가 일정하지 않은 원 데이터(irir.data)를 표준정규분포 데이터로 변환 

In [65]:
# 그럼 다시 해줘야 하는 과정 
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    iris_std, iris.target, random_state=2021, test_size=0.2, stratify = iris.target
)

In [77]:
lrc3 = LogisticRegression(random_state=2021)    # 모델 만들어주기(랜덤) 
lrc3.fit(X_train2, y_train2)    

LogisticRegression(random_state=2021)

In [78]:
pred_lr3 = lrc3.predict(X_test2)
accuracy_score(y_test2, pred_lr3)

0.9

예측결과 비교

In [80]:
df['SVC'] = pred_sv
df['LR2'] = pred_lr2
df['y2'] = y_test2
df['LR3'] = pred_lrc3
df.head()

y  DT  SVC  LR2  y2  LR3
0  0   0    0    0   0    0
1  1   1    1    1   1    0
2  1   2    1    1   1    0
3  2   2    2    2   2    0
4  0   0    0    0   0    0

In [ ]:
# lr / lrc 구분.. 

